//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealFontShoppingMall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font
    {
        public Font()
        {
            this.FontPhoto = new HashSet<FontPhoto>();
            this.MyFont = new HashSet<MyFont>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int seq { get; set; }
        public Nullable<int> brand_seq { get; set; }
        public Nullable<int> is_free { get; set; }
        public Nullable<int> is_personal { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> price_commercial { get; set; }
        public string os { get; set; }
        public string format { get; set; }
        public Nullable<int> period { get; set; }
        public string seller_name { get; set; }
        public string file_url { get; set; }
        public string info { get; set; }
        public string intro { get; set; }
        public string link_url { get; set; }
        public Nullable<int> click_count { get; set; }
        public Nullable<int> important_point { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<FontPhoto> FontPhoto { get; set; }
        public virtual ICollection<MyFont> MyFont { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
