//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealFontShoppingMall
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealFontShoppingmallEntities : DbContext
    {
        public RealFontShoppingmallEntities()
            : base("name=RealFontShoppingmallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<BlogPhoto> BlogPhoto { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Cs> Cs { get; set; }
        public virtual DbSet<Font> Font { get; set; }
        public virtual DbSet<FontPhoto> FontPhoto { get; set; }
        public virtual DbSet<MyFont> MyFont { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
